package com.jshop.entity;

// Generated 2012-8-22 20:51:22 by Hibernate Tools 3.4.0.CR1

/**
 * LocationT generated by hbm2java
 */
public class LocationT implements java.io.Serializable {

	private String lid;
	private String userid;
	private String username;
	private double lat;
	private double lng;
	private int zoom;
	private int versiont;

	public LocationT() {
	}

	public LocationT(String lid, String userid, String username, double lat,
			double lng, int zoom, int versiont) {
		this.lid = lid;
		this.userid = userid;
		this.username = username;
		this.lat = lat;
		this.lng = lng;
		this.zoom = zoom;
		this.versiont = versiont;
	}

	public String getLid() {
		return this.lid;
	}

	public void setLid(String lid) {
		this.lid = lid;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLng() {
		return this.lng;
	}

	public void setLng(double lng) {
		this.lng = lng;
	}

	public int getZoom() {
		return this.zoom;
	}

	public void setZoom(int zoom) {
		this.zoom = zoom;
	}

	public int getVersiont() {
		return this.versiont;
	}

	public void setVersiont(int versiont) {
		this.versiont = versiont;
	}

}
