package com.jshop.entity;

// Generated 2012-8-2 9:31:29 by Hibernate Tools 3.4.0.CR1

/**
 * GlobalParamM generated by hbm2java
 */
public class GlobalParamM implements java.io.Serializable {

	private String gkey;
	private String gvalue;

	public GlobalParamM() {
	}

	public GlobalParamM(String gkey, String gvalue) {
		this.gkey = gkey;
		this.gvalue = gvalue;
	}

	public String getGkey() {
		return this.gkey;
	}

	public void setGkey(String gkey) {
		this.gkey = gkey;
	}

	public String getGvalue() {
		return this.gvalue;
	}

	public void setGvalue(String gvalue) {
		this.gvalue = gvalue;
	}

}
